server {
    listen 80;
    server_name localhost;
    root /srv/sylius/public;
    index index.php index.html;

    # TIMEOUTS 600s (10min)
    client_max_body_size 300M;
    client_body_timeout 600s;
    client_header_timeout 600s;
    send_timeout 600s;
    keepalive_timeout 600s;
    
    # PHP-FPM
    location ~ \.php$ {
        fastcgi_pass php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
        
        # TIMEOUTS PHP-FPM
        fastcgi_read_timeout 600s;
        fastcgi_connect_timeout 600s;
        fastcgi_send_timeout 600s;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }
}
